/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MysticMart.gui.Manager.ManageCashierFrame;

import MysticMart.gui.Manager.ManageEmployeeFrames.AddEmployeesFrame;
import MysticMart.gui.Manager.ManageEmployeeFrames.ViewEmployeesFrame;
import MysticMart.gui.Manager.ManagerLoginFrame;
import MysticMart.gui.Manager.ManagerOptionsFrame;
import MysticMart.pojo.UserProfile;
import java.awt.Color;

/**
 *
 * @author prach
 */
public class ManageCashierFrame extends javax.swing.JFrame {

    /**
     * Creates new form ManageCashierFrame
     */
    public ManageCashierFrame() {
        super("Manage cashier frame");
        initComponents();
        this.setLocationRelativeTo(null);
        lblUsername.setText("Hey, "+UserProfile.getUsername());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        lblExit = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        BtnViewCashier = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        BtnUpdateCashier = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        BtnRemoveCashier = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        backBtn = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        DesignPanel4 = new javax.swing.JPanel();
        DesignPanel5 = new javax.swing.JPanel();
        BtnAddCashier = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1020, 5));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(199, 225, 186));
        jPanel2.setForeground(new java.awt.Color(221, 196, 112));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MysticMart/icons/headerLogo.png"))); // NOI18N
        jLabel8.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        lblExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MysticMart/icons/exit.png"))); // NOI18N
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
        });

        lblUsername.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 3, 16)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(0, 0, 0));
        lblUsername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsername.setText("Hey, @n null");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 899, Short.MAX_VALUE)
                .addComponent(lblExit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(426, 426, 426)
                    .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(426, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(lblExit, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(7, 7, 7)
                    .addComponent(lblUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(8, 8, 8)))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 40));

        logoutBtn.setBackground(new java.awt.Color(204, 110, 85));
        logoutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutBtnMouseExited(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Logout");

        javax.swing.GroupLayout logoutBtnLayout = new javax.swing.GroupLayout(logoutBtn);
        logoutBtn.setLayout(logoutBtnLayout);
        logoutBtnLayout.setHorizontalGroup(
            logoutBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoutBtnLayout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
        logoutBtnLayout.setVerticalGroup(
            logoutBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(logoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 470, 210, 40));

        BtnViewCashier.setBackground(new java.awt.Color(91, 125, 202));
        BtnViewCashier.setPreferredSize(new java.awt.Dimension(201, 30));
        BtnViewCashier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnViewCashierMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnViewCashierMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnViewCashierMouseExited(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("View Cashier");

        javax.swing.GroupLayout BtnViewCashierLayout = new javax.swing.GroupLayout(BtnViewCashier);
        BtnViewCashier.setLayout(BtnViewCashierLayout);
        BtnViewCashierLayout.setHorizontalGroup(
            BtnViewCashierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnViewCashierLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel10)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        BtnViewCashierLayout.setVerticalGroup(
            BtnViewCashierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BtnViewCashierLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addContainerGap())
        );

        jPanel1.add(BtnViewCashier, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 180, -1));

        BtnUpdateCashier.setBackground(new java.awt.Color(91, 125, 202));
        BtnUpdateCashier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnUpdateCashierMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnUpdateCashierMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnUpdateCashierMouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Update Cashier");

        javax.swing.GroupLayout BtnUpdateCashierLayout = new javax.swing.GroupLayout(BtnUpdateCashier);
        BtnUpdateCashier.setLayout(BtnUpdateCashierLayout);
        BtnUpdateCashierLayout.setHorizontalGroup(
            BtnUpdateCashierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BtnUpdateCashierLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(30, 30, 30))
        );
        BtnUpdateCashierLayout.setVerticalGroup(
            BtnUpdateCashierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnUpdateCashierLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(BtnUpdateCashier, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, 180, 30));

        BtnRemoveCashier.setBackground(new java.awt.Color(91, 125, 202));
        BtnRemoveCashier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnRemoveCashierMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnRemoveCashierMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnRemoveCashierMouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Remove Cashier");

        javax.swing.GroupLayout BtnRemoveCashierLayout = new javax.swing.GroupLayout(BtnRemoveCashier);
        BtnRemoveCashier.setLayout(BtnRemoveCashierLayout);
        BtnRemoveCashierLayout.setHorizontalGroup(
            BtnRemoveCashierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnRemoveCashierLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel6)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        BtnRemoveCashierLayout.setVerticalGroup(
            BtnRemoveCashierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnRemoveCashierLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(BtnRemoveCashier, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, 180, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MysticMart/icons/RemoveEmp.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, -1, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MysticMart/icons/ViewEmp.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(10, 10));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 90, 90));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MysticMart/icons/UpdateEmp.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 100, 100));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MysticMart/icons/AddEmp.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 100, 90));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MysticMart/icons/ManageCashierFrame.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 150, 470, 370));

        backBtn.setBackground(new java.awt.Color(221, 196, 112));
        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backBtnMouseExited(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Back");

        javax.swing.GroupLayout backBtnLayout = new javax.swing.GroupLayout(backBtn);
        backBtn.setLayout(backBtnLayout);
        backBtnLayout.setHorizontalGroup(
            backBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backBtnLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jLabel12)
                .addContainerGap(86, Short.MAX_VALUE))
        );
        backBtnLayout.setVerticalGroup(
            backBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 470, 210, 40));

        jLabel14.setFont(new java.awt.Font("MV Boli", 1, 27)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(105, 22, 79));
        jLabel14.setText("Welcome to our Cashiers Panel ");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 440, -1));

        DesignPanel4.setBackground(new java.awt.Color(221, 196, 112));

        javax.swing.GroupLayout DesignPanel4Layout = new javax.swing.GroupLayout(DesignPanel4);
        DesignPanel4.setLayout(DesignPanel4Layout);
        DesignPanel4Layout.setHorizontalGroup(
            DesignPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        DesignPanel4Layout.setVerticalGroup(
            DesignPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel1.add(DesignPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 60, -1, -1));

        DesignPanel5.setBackground(new java.awt.Color(243, 213, 189));

        javax.swing.GroupLayout DesignPanel5Layout = new javax.swing.GroupLayout(DesignPanel5);
        DesignPanel5.setLayout(DesignPanel5Layout);
        DesignPanel5Layout.setHorizontalGroup(
            DesignPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        DesignPanel5Layout.setVerticalGroup(
            DesignPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel1.add(DesignPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 250, 5));

        BtnAddCashier.setBackground(new java.awt.Color(91, 125, 202));
        BtnAddCashier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnAddCashierMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnAddCashierMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnAddCashierMouseExited(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Add Cashier");

        javax.swing.GroupLayout BtnAddCashierLayout = new javax.swing.GroupLayout(BtnAddCashier);
        BtnAddCashier.setLayout(BtnAddCashierLayout);
        BtnAddCashierLayout.setHorizontalGroup(
            BtnAddCashierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BtnAddCashierLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(41, 41, 41))
        );
        BtnAddCashierLayout.setVerticalGroup(
            BtnAddCashierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnAddCashierLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(BtnAddCashier, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 180, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1090, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblExitMouseClicked

    private void logoutBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnMouseClicked
        new ManagerLoginFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutBtnMouseClicked

    private void logoutBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnMouseEntered
        logoutBtn.setBackground(new Color(219, 154, 136));
    }//GEN-LAST:event_logoutBtnMouseEntered

    private void logoutBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnMouseExited
        logoutBtn.setBackground(new Color(204,110,85));
    }//GEN-LAST:event_logoutBtnMouseExited

    private void BtnViewCashierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnViewCashierMouseClicked
        new ViewCashierFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnViewCashierMouseClicked

    private void BtnViewCashierMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnViewCashierMouseEntered
        BtnViewCashier.setBackground(new Color(117, 131, 183));
    }//GEN-LAST:event_BtnViewCashierMouseEntered

    private void BtnViewCashierMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnViewCashierMouseExited
        BtnViewCashier.setBackground(new Color(91,125,202));
    }//GEN-LAST:event_BtnViewCashierMouseExited

    private void BtnUpdateCashierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnUpdateCashierMouseClicked
        new UpdateCashierFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnUpdateCashierMouseClicked

    private void BtnUpdateCashierMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnUpdateCashierMouseEntered
        BtnUpdateCashier.setBackground(new Color(117, 131, 183));
    }//GEN-LAST:event_BtnUpdateCashierMouseEntered

    private void BtnUpdateCashierMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnUpdateCashierMouseExited
        BtnUpdateCashier.setBackground(new Color(91,125,202));
    }//GEN-LAST:event_BtnUpdateCashierMouseExited

    private void BtnRemoveCashierMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnRemoveCashierMouseEntered
        BtnRemoveCashier.setBackground(new Color(117, 131, 183));
    }//GEN-LAST:event_BtnRemoveCashierMouseEntered

    private void BtnRemoveCashierMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnRemoveCashierMouseExited
        BtnRemoveCashier.setBackground(new Color(91,125,202));
    }//GEN-LAST:event_BtnRemoveCashierMouseExited

    private void backBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseClicked
        new ManagerOptionsFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnMouseClicked

    private void backBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseEntered
        backBtn.setBackground(new Color(186,177,144));
    }//GEN-LAST:event_backBtnMouseEntered

    private void backBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseExited
        backBtn.setBackground(new Color(221,196,112));
    }//GEN-LAST:event_backBtnMouseExited

    private void BtnRemoveCashierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnRemoveCashierMouseClicked
        new RemoveCashierFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnRemoveCashierMouseClicked

    private void BtnAddCashierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAddCashierMouseClicked
        new AddCashierFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnAddCashierMouseClicked

    private void BtnAddCashierMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAddCashierMouseEntered
        BtnAddCashier.setBackground(new Color(117, 131, 183));
    }//GEN-LAST:event_BtnAddCashierMouseEntered

    private void BtnAddCashierMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAddCashierMouseExited
        BtnAddCashier.setBackground(new Color(91,125,202));
    }//GEN-LAST:event_BtnAddCashierMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageCashierFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageCashierFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageCashierFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageCashierFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageCashierFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BtnAddCashier;
    private javax.swing.JPanel BtnRemoveCashier;
    private javax.swing.JPanel BtnUpdateCashier;
    private javax.swing.JPanel BtnViewCashier;
    private javax.swing.JPanel DesignPanel4;
    private javax.swing.JPanel DesignPanel5;
    private javax.swing.JPanel backBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel logoutBtn;
    // End of variables declaration//GEN-END:variables
}
